#/srv/gitlab/data /var/opt/gitlab For storing application data
#/srv/gitlab/logs /var/log/gitlab For storing logs
#/srv/gitlab/config /etc/gitlab For storing the GitLab configuration file
#/srv/gitlab/config/ssl/gitlab.example.com.crt
#/srv/gitlab/config/ssl/gitlab.example.com.key
# https://docs.gitlab.com/omnibus/docker/
#https://github.com/sameersbn/docker-gitlab
# voir ce site pour le détai lde la génération ssl elle est simplifié vu qu'il n'y a pas de CA
web:
  image: 'gitlab/gitlab-ce:latest'
  hostname: 'gitlab.example.com'
  ports:
  - '80:80'
  - '443:443'
  - '22:22'
  - "5005:5005"
  volumes:
    - './gitlab/config:/etc/gitlab'
    - './gitlab/logs:/var/log/gitlab'
    - './gitlab/data:/var/opt/gitlab'
