web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.dev.local'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.dev.local'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
    - '5005:5005'
  volumes:
    - '/media/mickael/Perso/Workspace/Admin Linux/Docker/DockerGitlab/config:/etc/gitlab'
    - '/media/mickael/Perso/Workspace/Admin Linux/Docker/DockerGitlab/logs:/var/log/gitlab'
    - '/media/mickael/Perso/Workspace/Admin Linux/Docker/DockerGitlab/data:/var/opt/gitlab'
